title: Battle of the {Brain-Model-Mapping} Metrics (BotBM3)
description: Community Event @ Cognitive Computational Neuroscience (CCN2024)

timezone: US/Eastern

navigation:
  Overview: "/"
  Schedule: "/schedule"
  Talk Series: "/talkseries"
  What is BotBM3?: "/whatisthis"

markdown: kramdown

github:
  repository: https://github.com/BotBM3

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

destination: _website/

favicon: assets/images/favicon/gradient-96.png

exclude: ['setup', 'code', '*draft', '*xylo*', 'README.md', 'Gemfile', 'Gemfile.lock']
